export const PRODUCTS_SET_LIST = 'PRODUCTS_SET_LIST';
export const PRODUCTS_ADD_LIST = 'PRODUCTS_ADD_LIST';
export const PRODUCTS_CLOSE_LIST = 'PRODUCTS_CLOSE_LIST';
export const PRODUCTS_SET_LIST_SCROLL = 'PRODUCTS_SET_LIST_SCROLL';
export const PRODUCTS_INCREASE_LIST_LENGTH = 'PRODUCTS_INCREASE_LIST_LENGTH';
export const PRODUCTS_SET_OPENED_PRODUCT = 'PRODUCTS_SET_OPENED_PRODUCT';
export const PRODUCTS_CLOSE_PRODUCT = 'PRODUCTS_CLOSE_PRODUCT';

//Auth
export const AUTH_SET_PAYLOAD = 'AUTH_SET_PAYLOAD';
export const AUTH_SET_CALLBACK_ON_SUCCEESS = 'AUTH_SET_CALLBACK_ON_SUCCEESS';
export const AUTH_CLEAR_CALLBACK_ON_SUCCEESS = 'AUTH_CLEAR_CALLBACK_ON_SUCCEESS';
export const AUTH_SET_FAKE_ACTION = 'AUTH_SET_FAKE_ACTION';

// User
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_SET_MY_ID = 'USER_SET_MY_ID';
export const USER_SET_PROFILE = 'USER_SET_PROFILE';
export const USER_RECEIVE_PROFILE = 'USER_RECEIVE_PROFILE';
export const USER_SET_PHOTOS_CONFIG = 'USER_SET_PHOTOS_CONFIG';
export const USER_CLOSE_PROFILE = 'USER_CLOSE_PROFILE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_MY_CURRENT_LIST = 'USER_SET_MY_CURRENT_LIST';
export const USER_SET_TOOLTIP = 'USER_SET_TOOLTIP';
export const USER_SET_PAYMENT = 'USER_SET_PAYMENT';
export const USER_SET_USE_DAYS = 'USER_SET_USE_DAYS';
export const USER_SET_SUPPLIER_STATUS = 'USER_SET_SUPPLIER_STATUS';
export const USER_SHOW_MENU = 'USER_SHOW_MENU';

//Lead
export const LEAD_INIT = 'LEAD_INIT';
export const LEAD_RECEIVE = 'LEAD_RECEIVE';
export const LEAD_SET_TAB = 'LEAD_SET_TAB';
export const LEAD_INC_NOTIFY = 'LEAD_INC_NOTIFY';
export const LEAD_CLEAR_NOTIFY = 'LEAD_CLEAR_NOTIFY';
export const LEAD_INC_LENGTH_LIST = 'LEAD_INC_LENGTH_LIST';
export const LEAD_UPDATE = 'LEAD_UPDATE';
export const LEAD_SET_SCROLL = 'LEAD_SET_SCROLL';
export const LEAD_CLOSE = 'LEAD_CLOSE';

//Conversation
export const CONVERSATION_SET = 'CONVERSATION_SET';
export const CONVERSATION_SET_ACTION = 'CONVERSATION_SET_ACTION';
export const CONVERSATION_SET_ACTION_DATA = 'CONVERSATION_SET_ACTION_DATA';
export const CONVERSATION_RECEIVE_MESSAGE = 'CONVERSATION_RECEIVE_MESSAGE';
export const CONVERSATION_LOAD_MESSAGE = 'CONVERSATION_LOAD_MESSAGE';
export const CONVERSATION_SET_SHOW_MENU = 'CONVERSATION_SET_SHOW_MENU';
export const CONVERSATION_SET_SHOW_STATUS_MENU = 'CONVERSATION_SET_SHOW_STATUS_MENU';
export const CONVERSATION_SET_SHOW_CANCEL_MENU = 'CONVERSATION_SET_SHOW_CANCEL_MENU';
export const CONVERSATION_CONFIRM_MSG = 'CONVERSATION_CONFIRM_MSG';
export const CONVERSATION_CONFIRM_STATUS_MSG = 'CONVERSATION_CONFIRM_STATUS_MSG';
export const CONVERSATION_INC_LENGTH_LIST = 'CONVERSATION_INC_LENGTH_LIST';
export const CONVERSATION_SEND_STATUS = 'CONVERSATION_SEND_STATUS';
export const CONVERSATION_OPEN_IMG_POPUP = 'CONVERSATION_OPEN_IMG_POPUP';
export const CONVERSATION_CLOSE = 'CONVERSATION_CLOSE';
export const CONVERSATION_SET_IMG_LOADER = 'CONVERSATION_SET_IMG_LOADER';
export const CONVERSATION_CLOSE_IMG_POPUP = 'CONVERSATION_CLOSE_IMG_POPUP';


export const MONETIZATION_SET_STATUS = 'MONETIZATION_SET_STATUS';




// Search
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const SELECT_TAG = 'SELECT_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SEARCH_SET_PENDING = 'SEARCH_SET_PENDING';
