export const PRODUCTS_SET_LIST = 'PRODUCTS_SET_LIST';
export const PRODUCTS_ADD_LIST = 'PRODUCTS_ADD_LIST';
export const PRODUCTS_CLOSE_LIST = 'PRODUCTS_CLOSE_LIST';
export const PRODUCTS_SET_LIST_SCROLL = 'PRODUCTS_SET_LIST_SCROLL';
export const PRODUCTS_INCREASE_LIST_LENGTH = 'PRODUCTS_INCREASE_LIST_LENGTH';


export const USER_SET_PROFILE = 'USER_SET_PROFILE';
export const USER_ADD_PROFILE = 'USER_ADD_PROFILE';
