export const PRODUCTS_SET_LIST = 'PRODUCTS_SET_LIST';
export const PRODUCTS_ADD_LIST = 'PRODUCTS_ADD_LIST';
export const PRODUCTS_CLOSE_LIST = 'PRODUCTS_CLOSE_LIST';
export const PRODUCTS_SET_LIST_SCROLL = 'PRODUCTS_SET_LIST_SCROLL';
